parameters:
    database_host:     container-with-mysql
    database_port:     3306
    database_name:     symfony
    database_user:     symfony
    database_password: symfony
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    # A secret key that's used to generate certain security-related tokens
    secret:            SecretSymfonyHash
